
const cards = [
    { name: "Two", value: 2, owner: "deck", suit: 'Hearts' },
    { name: "Three", value: 3, owner: "deck", suit: 'Hearts' },
    { name: "Four", value: 4, owner: "deck", suit: 'Hearts' },
    { name: "Five", value: 5, owner: "deck", suit: 'Hearts' },
    { name: "Six", value: 6, owner: "deck", suit: 'Hearts' },
    { name: "Seven", value: 7, owner: "deck", suit: 'Hearts' },
    { name: "Eight", value: 8, owner: "deck", suit: 'Hearts' },
    { name: "Nine", value: 9, owner: "deck", suit: 'Hearts' },
    { name: "Ten", value: 10, owner: "deck", suit: 'Hearts' },
    { name: "Jack", value: 11, owner: "deck", suit: 'Hearts' },
    { name: "Queen", value: 12, owner: "deck", suit: 'Hearts' },
    { name: "King", value: 13, owner: "deck", suit: 'Hearts' },
    { name: "Ace", value: 14, owner: "deck", suit: 'Hearts' },
    { name: "Two", value: 2, owner: "deck", suit: 'Diamonds' },
    { name: "Three", value: 3, owner: "deck", suit: 'Diamonds' },
    { name: "Four", value: 4, owner: "deck", suit: 'Diamonds' },
    { name: "Five", value: 5, owner: "deck", suit: 'Diamonds' },
    { name: "Six", value: 6, owner: "deck", suit: 'Diamonds' },
    { name: "Seven", value: 7, owner: "deck", suit: 'Diamonds' },
    { name: "Eight", value: 8, owner: "deck", suit: 'Diamonds' },
    { name: "Nine", value: 9, owner: "deck", suit: 'Diamonds' },
    { name: "Ten", value: 10, owner: "deck", suit: 'Diamonds' },
    { name: "Jack", value: 11, owner: "deck", suit: 'Diamonds' },
    { name: "Queen", value: 12, owner: "deck", suit: 'Diamonds' },
    { name: "King", value: 13, owner: "deck", suit: 'Diamonds' },
    { name: "Ace", value: 14, owner: "deck", suit: 'Diamonds' },
    { name: "Two", value: 2, owner: "deck", suit: 'Clubs' },
    { name: "Three", value: 3, owner: "deck", suit: 'Clubs' },
    { name: "Four", value: 4, owner: "deck", suit: 'Clubs' },
    { name: "Five", value: 5, owner: "deck", suit: 'Clubs' },
    { name: "Six", value: 6, owner: "deck", suit: 'Clubs' },
    { name: "Seven", value: 7, owner: "deck", suit: 'Clubs' },
    { name: "Eight", value: 8, owner: "deck", suit: 'Clubs' },
    { name: "Nine", value: 9, owner: "deck", suit: 'Clubs' },
    { name: "Ten", value: 10, owner: "deck", suit: 'Clubs' },
    { name: "Jack", value: 11, owner: "deck", suit: 'Clubs' },
    { name: "Queen", value: 12, owner: "deck", suit: 'Clubs' },
    { name: "King", value: 13, owner: "deck", suit: 'Clubs' },
    { name: "Ace", value: 14, owner: "deck", suit: 'Clubs' },
    { name: "Two", value: 2, owner: "deck", suit: 'Spades' },
    { name: "Three", value: 3, owner: "deck", suit: 'Spades' },
    { name: "Four", value: 4, owner: "deck", suit: 'Spades' },
    { name: "Five", value: 5, owner: "deck", suit: 'Spades' },
    { name: "Six", value: 6, owner: "deck", suit: 'Spades' },
    { name: "Seven", value: 7, owner: "deck", suit: 'Spades' },
    { name: "Eight", value: 8, owner: "deck", suit: 'Spades' },
    { name: "Nine", value: 9, owner: "deck", suit: 'Spades' },
    { name: "Ten", value: 10, owner: "deck", suit: 'Spades' },
    { name: "Jack", value: 11, owner: "deck", suit: 'Spades' },
    { name: "Queen", value: 12, owner: "deck", suit: 'Spades' },
    { name: "King", value: 13, owner: "deck", suit: 'Spades' },
    { name: "Ace", value: 14, owner: "deck", suit: 'Spades' }
];

//exports.cards = cards;
module.exports = { cards }